### ISSUE TITLE
Graphviz `.dot` export

### ISSUE THREAD

**Issue by holzkohlengrill** [bmwcarit/Emma#19]
## Feature Description

In order to give the user a better understanding about overlaps, containments and duplicates a graphical visualisation would help. Currently this is only possible by viewing the `.csv` file (-> textual representation).

In small projects it is still easy to keep an overview however when projects grow this can happen hundreds of times.

Another alternative or complementary solution would be to reshape or add some information that tools like [Gephi](https://gephi.org/) could import the `.csv` and/or `.dot` file.

The great thing here about the `.csv` import is that you can switch from graphical to "data laboratory" representation (and back) and get more information about this specific element in this view.

Note about Gephi DOT support:
> Gephi currently doesn’t provide a complete support of the DOT format. Subgraphs are not supported, nor custom attributes or size. Only labels and colors are imported if present. Directed and undirected graphs are supported.
> 
> From: https://gephi.org/users/supported-graph-formats/graphviz-dot-format/

`emma_libs/memoryManager.py:156` is a good place to get started with the implementation.

# Dot viewers / extensions
* [Gephi](https://gephi.org/) (cross-platform)
* [ZGRViewer](http://zvtm.sourceforge.net/zgrviewer.html) (cross-platform)
* [Graphviz Preview](https://github.com/EFanZh/Graphviz-Preview) (VSCode preview plugin; cross-platform)

# References
* [DOT format spec](https://graphviz.gitlab.io/_pages/doc/info/lang.html)
* [Graphviz Python lib](https://graphviz.readthedocs.io/en/stable/index.html) (MIT licenced)

# TODOs

* [ ] Decide if both or only one solution should be implemented
* [x] Document if external libraries are used (like `graphviz` (MIT) for dot files); decide whether we need an external library
* [ ] Write the implementation for generation
* [ ] Include a new command line argument to actiavte the output
* [ ] Document the shape/colour syntax
* [ ] Write tests

**Comment by holzkohlengrill** [comment]
Licence part to add for table in README.md
```
| Graphviz (v0.11.1+)  | [graphviz](https://pypi.org/project/graphviz/)      | MIT                                  | [https://github.com/xflr6/graphviz](https://github.com/xflr6/graphviz)                                                                                                                       |

```

**Comment by holzkohlengrill** [comment]
Will be realised on other form via #52
