### ISSUE TITLE
Add GCC compiler support

### ISSUE THREAD

**Issue by holzkohlengrill** [bmwcarit/Emma#32]
## Feature Description

With the memory manager redesign (issue #5 ) we smoothed the ways for implementing a parser (memory manager) for GCC.

See also this issue: https://cc-github.bmwgroup.net/marcelschmalzlpartner/MAdZ/issues/74

# TODOs
* [ ] Implement a GCC parser (analogous to the preexisting one)
* [ ] Add a new test project for GCC
* [ ] Document licences (see also below)
* [ ] Write unit tests and functional tests
* [ ] Test new implementation

==

Infineon XMC 2Go blinky project licence:

```text
| test_project_gcc (v1.3+) | Map files based on XMC 2Go Initial Start project   | No       | BSD-3-Clause  | [Infineon -> Documents -> XMC 2Go Initial Start](https://www.infineon.com/cms/en/product/evaluation-boards/kit_xmc_2go_xmc1100_v1/#!documents)                                                                                                                          |
```

**Comment by shreyasbharath** [comment]
How far away is this? ARM GCC support would be fantastic!

**Comment by holzkohlengrill** [comment]
@shreyasbharath thanks for your interest in Emma. This ticket is still in our [backlog](https://github.com/bmwcarit/Emma/projects/1) since we hat other priorities. Meaning it will still take some time.

If you have some time we are looking forward to receive contributions. You will find all information about introducing new compilers here: [https://github.com/bmwcarit/Emma/blob/master/doc/dev-guide.md#adding-compiler-support](https://github.com/bmwcarit/Emma/blob/master/doc/dev-guide.md#adding-compiler-support)

As a workaround: If you manage to tweak the GCC map file output to be in one line per section/object and that sections and objects could be distinguished by different parsing regexes you could already use Emma as it is.
