### ISSUE TITLE
Improve user experience

### ISSUE THREAD

**Issue by holzkohlengrill** [bmwcarit/Emma#47]
## Feature Description
We want a stable and comfortable user interface which can compare quickly and easily Emma analyses.

The current user interface is quite rudamentary.

## ToDo's
- [ ] Test suitable libraries
- [ ] Check licence
- [ ] Write unit tests
- [x] Implement the change according to #14 

See also this ancient issue for more details (note: not everything is still up-to-date what is stated there): https://cc-github.bmwgroup.net/marcelschmalzlpartner/MAdZ/issues/45

Consider also the thoughts in: https://cc-github.bmwgroup.net/marcelschmalzlpartner/MAdZ/issues/44

## Some links to start with
* https://github.com/CITGuru/PyInquirer
* https://docs.python.org/3/library/curses.html
